version: '3'
services:
  db:
    image: postgres
  server:
    build: .
    #command: /bin/bash
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0' && bin/webpack-dev-server"
    volumes:
      - .:/appname
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
    tty: true

