version: '3'
services:
  db:
    image: postgres
  server:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/appname
    ports:
      - "3000:3000"
    depends_on:
      - db

